"""
Feasibility report generation (PDF via reportlab, Word via python-docx).

Both generators return raw bytes so the API layer can stream them without
touching the filesystem. Bilingual: locale "ar" renders Arabic labels and
right-alignment; "en" renders English. Arabic glyph shaping is applied when
arabic_reshaper + python-bidi are available and gracefully degrades to
unshaped text otherwise, so report generation never hard-fails on a slim runtime.

No invented numbers: every figure comes from the persisted study/result. Missing
values are rendered as a dash rather than fabricated.
"""
from __future__ import annotations

import io
from typing import Any, Dict, Optional

try:  # pragma: no cover
    import arabic_reshaper  # type: ignore
    from bidi.algorithm import get_display  # type: ignore

    def _shape_ar(text: str) -> str:
        try:
            return get_display(arabic_reshaper.reshape(text))
        except Exception:
            return text
except Exception:  # pragma: no cover

    def _shape_ar(text: str) -> str:
        return text


LABELS = {
    "ar": {
        "title": "دراسة جدوى",
        "brand": "سعودي بزنس",
        "project": "المشروع",
        "industry": "القطاع",
        "investment": "الاستثمار",
        "type": "نوع الدراسة",
        "status": "الحالة",
        "results": "النتائج المالية",
        "roi": "العائد على الاستثمار %",
        "payback": "فترة الاسترداد (سنوات)",
        "npv": "صافي القيمة الحالية",
        "irr": "معدل العائد الداخلي %",
        "verdict": "الحكم",
        "no_result": "لم يتم احتساب النتائج المالية بعد.",
        "disclaimer": "هذا التقرير أداة مساعدة ولا يُعدّ استشارة.",
        "generated": "تم الإنشاء بواسطة منصة سعودي بزنس",
    },
    "en": {
        "title": "Feasibility Study",
        "brand": "Saudi Business",
        "project": "Project",
        "industry": "Industry",
        "investment": "Investment",
        "type": "Study type",
        "status": "Status",
        "results": "Financial Results",
        "roi": "ROI %",
        "payback": "Payback (years)",
        "npv": "Net Present Value",
        "irr": "IRR %",
        "verdict": "Verdict",
        "no_result": "Financial results have not been computed yet.",
        "disclaimer": "This report is an assistive tool and is not legal, financial, or tax advice.",
        "generated": "Generated by the Saudi Business platform",
    },
}
def _fmt(value):
    if value is None:
        return "—"
    if isinstance(value, float):
        return format(value, ",.2f")
    return str(value)


def _dir_text(text, locale):
    return _shape_ar(text) if locale == "ar" else text


def build_report_context(study, result, project):
    payload = getattr(study, "payload", {}) or {}
    return {
        "title": getattr(study, "title", ""),
        "study_type": getattr(study, "study_type", "general"),
        "status": getattr(study, "status", "draft"),
        "project_name": getattr(project, "name", "") if project else payload.get("industry", ""),
        "industry": getattr(project, "industry", "") if project else payload.get("industry", ""),
        "investment": getattr(project, "investment", None) if project else payload.get("investment"),
        "result": result,
    }


def generate_pdf(ctx, locale="ar"):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    L = LABELS.get(locale, LABELS["en"])
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    right = width - 20 * mm
    left = 20 * mm
    y = [height - 25 * mm]

    def line(label, value, size=11):
        c.setFont("Helvetica", size)
        text = _dir_text(label, locale) + ": " + _dir_text(value, locale)
        if locale == "ar":
            c.drawRightString(right, y[0], text)
        else:
            c.drawString(left, y[0], text)
        y[0] -= 8 * mm

    c.setFont("Helvetica-Bold", 18)
    header = _dir_text(L["brand"], locale) + " - " + _dir_text(L["title"], locale)
    if locale == "ar":
        c.drawRightString(right, y[0], header)
    else:
        c.drawString(left, y[0], header)
    y[0] -= 14 * mm

    c.setFont("Helvetica-Bold", 13)
    if locale == "ar":
        c.drawRightString(right, y[0], _dir_text(ctx.get("title", ""), locale))
    else:
        c.drawString(left, y[0], ctx.get("title", ""))
    y[0] -= 12 * mm

    line(L["project"], _fmt(ctx.get("project_name")))
    line(L["industry"], _fmt(ctx.get("industry")))
    line(L["investment"], _fmt(ctx.get("investment")))
    line(L["type"], _fmt(ctx.get("study_type")))
    line(L["status"], _fmt(ctx.get("status")))
    y[0] -= 4 * mm

    c.setFont("Helvetica-Bold", 13)
    if locale == "ar":
        c.drawRightString(right, y[0], _dir_text(L["results"], locale))
    else:
        c.drawString(left, y[0], L["results"])
    y[0] -= 10 * mm

    result = ctx.get("result")
    if not result:
        line("", L["no_result"])
    else:
        line(L["roi"], _fmt(result.get("roi_percent")))
        line(L["payback"], _fmt(result.get("payback_years")))
        line(L["npv"], _fmt(result.get("npv")))
        line(L["irr"], _fmt(result.get("irr_percent")))
        line(L["verdict"], _fmt(result.get("verdict")))

    c.setFont("Helvetica-Oblique", 8)
    footer = _dir_text(L["disclaimer"], locale)
    if locale == "ar":
        c.drawRightString(right, 18 * mm, footer)
        c.drawRightString(right, 13 * mm, _dir_text(L["generated"], locale))
    else:
        c.drawString(left, 18 * mm, footer)
        c.drawString(left, 13 * mm, L["generated"])

    c.showPage()
    c.save()
    return buf.getvalue()
def generate_docx(ctx, locale="ar"):
    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt

    L = LABELS.get(locale, LABELS["en"])
    align = WD_ALIGN_PARAGRAPH.RIGHT if locale == "ar" else WD_ALIGN_PARAGRAPH.LEFT

    doc = Document()

    def para(text, bold=False, size=11):
        p = doc.add_paragraph()
        p.alignment = align
        run = p.add_run(text)
        run.bold = bold
        run.font.size = Pt(size)
        return p

    para(L["brand"] + " - " + L["title"], bold=True, size=18)
    para(ctx.get("title", ""), bold=True, size=14)
    para("")

    def field(label, value):
        para(label + ": " + value)

    field(L["project"], _fmt(ctx.get("project_name")))
    field(L["industry"], _fmt(ctx.get("industry")))
    field(L["investment"], _fmt(ctx.get("investment")))
    field(L["type"], _fmt(ctx.get("study_type")))
    field(L["status"], _fmt(ctx.get("status")))

    para("")
    para(L["results"], bold=True, size=14)

    result = ctx.get("result")
    if not result:
        para(L["no_result"])
    else:
        field(L["roi"], _fmt(result.get("roi_percent")))
        field(L["payback"], _fmt(result.get("payback_years")))
        field(L["npv"], _fmt(result.get("npv")))
        field(L["irr"], _fmt(result.get("irr_percent")))
        field(L["verdict"], _fmt(result.get("verdict")))

    para("")
    para(L["disclaimer"], size=8)
    para(L["generated"], size=8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_proposal_context(proposal):
    payload = proposal.payload or {}
    return {"title": proposal.title, "type": proposal.proposal_type, "status": proposal.status,
            "version": proposal.version, **payload}


def generate_proposal_pdf(ctx, locale="ar"):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas
    labels = {
        "ar": [("client_name", "العميل"), ("client_company", "الشركة"), ("scope", "نطاق العرض"),
               ("deliverables", "المخرجات"), ("methodology", "المنهجية"), ("price", "القيمة"),
               ("timeline", "الجدول الزمني"), ("terms", "الشروط")],
        "en": [("client_name", "Client"), ("client_company", "Company"), ("scope", "Scope"),
               ("deliverables", "Deliverables"), ("methodology", "Methodology"), ("price", "Value"),
               ("timeline", "Timeline"), ("terms", "Terms")],
    }
    buf = io.BytesIO(); c = canvas.Canvas(buf, pagesize=A4); width, height = A4
    left, right, y = 20 * mm, width - 20 * mm, height - 24 * mm
    def draw(text, bold=False, size=11):
        nonlocal y
        if y < 28 * mm: c.showPage(); y = height - 24 * mm
        c.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        value = _dir_text(str(text or "—")[:150], locale)
        (c.drawRightString(right, y, value) if locale == "ar" else c.drawString(left, y, value)); y -= 8 * mm
    draw(("سعودي بزنس — عرض للمستثمر" if locale == "ar" else "Saudi Business — Investor Proposal"), True, 18)
    draw(ctx.get("title"), True, 14); y -= 3 * mm
    for key, label in labels[locale if locale in labels else "en"]:
        value = ctx.get(key)
        if key == "price" and value: value = f"{value} {ctx.get('currency', 'SAR')}"
        draw(f"{label}: {value or '—'}")
    draw("هذا العرض معلوماتي ولا يمثل التزامًا استثماريًا أو ضمانًا للعائد." if locale == "ar" else "This proposal is informational and is not an investment commitment or return guarantee.", False, 8)
    c.showPage(); c.save(); return buf.getvalue()


def generate_proposal_docx(ctx, locale="ar"):
    from docx import Document as WordDocument
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt
    labels = {
        "ar": [("client_name", "العميل"), ("client_company", "الشركة"), ("scope", "نطاق العرض"), ("deliverables", "المخرجات"), ("methodology", "المنهجية"), ("price", "القيمة"), ("timeline", "الجدول الزمني"), ("terms", "الشروط")],
        "en": [("client_name", "Client"), ("client_company", "Company"), ("scope", "Scope"), ("deliverables", "Deliverables"), ("methodology", "Methodology"), ("price", "Value"), ("timeline", "Timeline"), ("terms", "Terms")],
    }
    doc = WordDocument(); align = WD_ALIGN_PARAGRAPH.RIGHT if locale == "ar" else WD_ALIGN_PARAGRAPH.LEFT
    def add(text, bold=False, size=11):
        p = doc.add_paragraph(); p.alignment = align; run = p.add_run(str(text)); run.bold = bold; run.font.size = Pt(size)
    add("سعودي بزنس — عرض للمستثمر" if locale == "ar" else "Saudi Business — Investor Proposal", True, 18)
    add(ctx.get("title", ""), True, 14)
    for key, label in labels[locale if locale in labels else "en"]:
        value = ctx.get(key) or "—"
        if key == "price" and value != "—": value = f"{value} {ctx.get('currency', 'SAR')}"
        add(f"{label}: {value}")
    add("هذا العرض معلوماتي ولا يمثل التزامًا استثماريًا أو ضمانًا للعائد." if locale == "ar" else "This proposal is informational and is not an investment commitment or return guarantee.", size=8)
    buf = io.BytesIO(); doc.save(buf); return buf.getvalue()
