"""Alembic migration environment.

Resolves the migration connection URL via app.db's shared resolver, which
prefers a DIRECT / NON-POOLING endpoint (POSTGRES_URL_NON_POOLING or
DIRECT_DATABASE_URL) before the pooled DATABASE_URL / POSTGRES_URL. DDL is run
over the direct endpoint because managed poolers (PgBouncer on Neon/Vercel)
cannot reliably execute migrations. The URL is never read from the ini file and
is never logged. Model metadata is exposed so migrations can be autogenerated.
"""
import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the backend package and the database/ package importable so we can load
# models + Base and the shared migration-URL resolver.
_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT / "backend"))
sys.path.insert(0, str(_REPO_ROOT / "database"))

from migration_url import resolve_migration_url  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Direct/non-pooling endpoint wins for DDL; falls back to DATABASE_URL/POSTGRES_URL.
_db_url = resolve_migration_url(os.environ)
if _db_url:
    config.set_main_option("sqlalchemy.url", _db_url)

from app.db import Base  # noqa: E402
from app import models  # noqa: E402,F401 (registers tables on Base.metadata)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
